Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -4,17 +4,22 @@ on:
   workflow_dispatch:
     inputs:
       new_version:
-        description: 'New release version (optional)'
+        description: "Create a new release version."
+        type: boolean
         required: false
-        
+        default: false
+      new_version_name:
+        description: 'Overwrite release version name (optional)'
+        required: false
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
-    permissions:  # Add this section for explicit permissions
-      contents: read  # Allow read access to the repository contents
-      issues: write    # Allow write access to issues
-      pull-requests: write  # Allow write access to pull requests
+    permissions:
+      contents: read
+      issues: write
+      pull-requests: write
       
     steps:
       - name: Checkout code
@@ -29,34 +34,65 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret
           password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret
 
-      - name: Set Branch Name
-        id: set_branch_name
+      - name: Get the latest release
+        id: get_release
         run: |
-          # Get the branch name from the context
-          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
-          echo "Branch name is $BRANCH_NAME" 
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
+          if [ "${{ github.event.inputs.new_version_name }}" == "" ]; then
+            # Get the latest release tag
+            LATEST_TAG=$(git fetch --tags && git tag -l --sort=-creatordate | head -n 1)
+            echo "Latest release tag: $LATEST_TAG"
 
+            # Extract major, minor, patch and pre-release
+            if [[ $LATEST_TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)([-_ ].*)?$ ]]; then
+                MAJOR=${BASH_REMATCH[1]}
+                MINOR=${BASH_REMATCH[2]}
+                PATCH=${BASH_REMATCH[3]}
+                PRE_RELEASE=${BASH_REMATCH[4]}
+                
+                if [ "$BRANCH_NAME" != "main" ] || [ -z "$PRE_RELEASE" ]; then
+                  # Increment the patch version
+                  NEW_PATCH=$((PATCH + 1))
+                else
+                  NEW_PATCH=$PATCH
+                fi
+
+                if [ "$BRANCH_NAME" != "main" ]; then
+                  PRE_RELEASE="_$BRANCH_NAME"
+                else
+                  PRE_RELEASE=""
+                fi
+
+                if [[ -n "$PRE_RELEASE" ]]; then
+                  NEW_TAG="$MAJOR.$MINOR.$NEW_PATCH$PRE_RELEASE"
+                else
+                  NEW_TAG="$MAJOR.$MINOR.$NEW_PATCH"
+                fi
+
+                NEW_TAG="${NEW_TAG// /_}"
+
+                echo "New release tag: $NEW_TAG"
+                echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
+            else
+                echo "Error: Latest tag format is invalid."
+                exit 1
+            fi
+          else
+              echo "new_tag=${{ github.event.inputs.new_version_name }}" >> $GITHUB_ENV
+          fi
+  
       - name: Create Release
         id: create_release
         run: |
-          SANITIZED_NEW_VERSION="${{ github.event.inputs.new_version }}"
-          SANITIZED_NEW_VERSION="${SANITIZED_NEW_VERSION// /_}"  # Replace spaces with underscores
-
-          if [ -n "$SANITIZED_NEW_VERSION" ]; then
-            echo "Creating new release: ${{ github.event.inputs.new_version }}"
-            echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
-            gh release create "$SANITIZED_NEW_VERSION" --target "$BRANCH_NAME"
+          if [ "${{ github.event.inputs.new_version }}" == "true" ] &&  [ -n "${{ env.new_tag }}" ]; then
+              echo "Creating new release: ${{ env.new_tag }}""
+              echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
+              gh release create "${{ env.new_tag }}" --target "$BRANCH_NAME" 
           else
             echo "Release creation skipped."
           fi
 
       - name: Build and Push Docker Image
         run: |
-          # Sanitize the new version by replacing spaces with underscores
-          SANITIZED_NEW_VERSION="${{ github.event.inputs.new_version }}"
-          SANITIZED_NEW_VERSION="${SANITIZED_NEW_VERSION// /_}"  # Replace spaces with underscores
-
           if [ "$BRANCH_NAME" == "main" ]; then
             IMAGE_TAG="cgfm/internxt-cli_rclone:latest"
           else
@@ -72,8 +108,8 @@ jobs:
           docker push $IMAGE_TAG
 
           # If new version is provided, tag with the new version as well
-          if [ -n "$SANITIZED_NEW_VERSION" ]; then
-            NEW_IMAGE_TAG="cgfm/internxt-cli_rclone:$SANITIZED_NEW_VERSION"
+          if [ "${{ github.event.inputs.new_version }}" == "true" ] &&  [ -n "${{ env.new_tag }}" ]; then
+            NEW_IMAGE_TAG="cgfm/internxt-cli_rclone:${{ env.new_tag }}"
             echo "Tagging image with new version: $NEW_IMAGE_TAG"
             docker tag $IMAGE_TAG $NEW_IMAGE_TAG
             docker push $NEW_IMAGE_TAG
